---
title: "Gift Travel in the U.S. Congress"
author: "Philip Moniz"
date: "6/5/2017"
output: pdf_document
bibliography: /Users/philipmoniz/Documents/Scholastic Scribblings/my_library.bib
casl: /Users/philipmoniz/Documents/Scholastic Scribblings/apsa.csl
---

When members of Congress travel abroad on official business, as part of what are called Congressional Delegations, CODELs in Capitol parlance, they must report this travel to the Clerk of the House. Scholars have investigated where, how often, for how long, and with whom, members travel abroad (see for example [@Alduncin2014; @Alduncin2017]). When they want to travel as part of a Congressional Delegation, members must first request permission and funding from the parent chamber or relevant committee. Members can also be asked by other members if they would like to participate in a delegation trip. Some CODELs are partisan, others are bipartisan, but they are usually conducted in groups, presumably for the purpose of learning something valuable to their jobs as legislators, though some members have been criticized by challengers for wasting taxpayer money on pleasure trips.

While members can apply for travel paid for by the federal government, there is another way that members can get out of the house: gift travel. Gift travel comprises journeys that are paid for by a non-governmental source, and these trips can be within or without the United States. According to Rule XXV, clause 5 of the Rules of the House of Representatives, members must disclose reimbursement for such travel within 15 days of return [@Wickham2015]. The Clerk of the House makes a report of these disclosures public on its website. Rule XXV is also clear that no such gift travel can be paid for by a registered lobbyist or by the agent of a foreign principal, and neither can a registered lobbyist or agent of a foreign principal be present at any time during the trip.

Gift travel must also be for the purpose of official business. Members are not supposed to accept reimbursement for trips conducted primarily for leisure or diversion; such trips, of course, would give the appearance of corruption. Gift travel allows non-governmental organizations, such as trade associations, non-profits, think tanks, and universities to invite members of Congress to conferences, conventions, dinners, and other types of event. But why do non-governmental organizations choose to fly members to their events? Are some members more likely to be invited than others, and if so, why?

Answers to basic questions such as "how much gift travel do members go on?" and "what organizations are the most popular sponsors" are unanswered in the literature on members' travel behavior. This paper will provide a first look at this specific kind of travel behavior. I will rely on the literature on foreign travel among members of Congress to inform my hypotheses about gift travel since foreign travel is the nearest thing to gift travel that scholars have studied. The key difference to keep in mind, however, is that delegation and committee travel are the product of members' initiative while gift travel starts, at least in theory, with the giver.

# The Causes of Gift Travel

Gifts imply relationships. In any gift-giving situation, there is a giver and a recipient. Gifts are usually given as an expression of love, respect, or appreciation, and while they are not given with the expectation of reimbursement, they can be given with the expectation of reciprocity [@Graeber2011]. The relevant question here is: "Which members are most likely to reciprocate a sponsor's gift?" Reciprocation in this situation would mean that the member had improved the chances that the sponsor's policy preferences became law. Members who have more power, such as party leaders and committee chairmen, would be the first place to look. As powerful members, it would make sense for them, ceteris paribus, to receive more invitations and to go on more gift journeys than less powerful members.

Following this logic, other types of member should also be better investments for sponsors who wish to provide opportunities to travel and see things outside of Washington. Members who are likely to stick around should be more attractive to sponsors for the simple reason that only members who are in office can provide reciprocal benefits to their sponsors. An advantage should therefore be given both to senior members and to members who win by large margins.

As Alduncin, Parker, and Theriault [-@Alduncin2017] point out, senior members may also be more likely to shift their attention toward legislation and policymaking, so there may be some causation going in the other direction; that is, senior members may cultivate relationships with travel-gifting interest groups because they want to learn about policy, or they want information gains from those interest groups [@Hall2006].

In addition, because members from ideologically aligned districts, those with large margins of victory, are more likely to pursue national-level policy issues [@Grimmer2013a], we should also expect safe members to build relationships with nongovernmental groups that can provide opportunities for travel, and therefore they should take more trips at the NGOs expense.

As for the effect of members' political ideology, there is an interesting difference in how ideology may come into play in foreign travel as opposed to gift travel. [@Alduncin2017] speculate that more ideologically extreme members would tend to travel abroad less because they would be less inclined to think that they had something to learn from how foreign countries do things. For instance, Alduncin, Parker, and Theriault [-@Alduncin2017] report that conservative Republicans have always been less likely to travel (18). The authors further speculate that, because foreign travel often entails flying with members of the other party, ideologically extreme members will travel less than more moderate members.

The first speculation applies partially to gift travel because some sponsored trips are to foreign countries for the purpose of learning about social and political life abroad; other trips, however, keep members in the United States, and can bring them to ideologically charged events, such as those held by think tanks like the Heritage Foundation. Therefore, because gift travel may be more conducive to ideology-affirming experiences than foreign travel, ideological members may be no different than moderate members in their quantity of travel.

Whether or not ideological members are advantaged over moderate members depends on the sponsor organizations and their motives. If sponsors as a group are highly ideological, and they seek out likeminded legislators in order to give them information subsidies [@Hall2006], then more ideological members should travel more. Our hypothesis will remain what previous literature has found, but with the thought in mind that the sponsor-led nature of gift travel may result in different patterns than foreign travel.

The second speculation is less obviously relevant than the first to gift travel because gift travel need not be conducted as part of a group, and sponsors decide the composition of the group if there is one. Bipartisan gift travel is not unheard of, however, as there are instances, such as the entire Indiana delegation going on a trip sponsored by a soybean farmers' trade association, where members of different parties travel together, but this appears to be the exception rather than the rule. Sponsors seem to hand-select which members they want to give to.

To reiterate the hypotheses: 1) Chairmen and ranking committee members will travel more. 2) Safe members will travel more. 3) Senior members will travel more. 4) Ideologically extreme members will travel less.

Following Alduncin, Parker, and Theriault [-@Alduncin2017], I run the analyses separately for the two parties under the assumption that these explanatory variables may operate differently within each party. However, I also include whole-chamber analyses for comparison.

# Data

The data for this analysis come from the website of the Clerk of the House. The Clerk publishes yearly all of the gift travel reports filed by House representatives. This paper will analyze the reports from a single Congress, the 114th (2015-2016), but the Clerk has reports stretching back to 2011. The data set for the 114th Congress provided by the Clerk contains over 4000 rows; each row represents a travel report. A quick glance at the data set reveals that many of these rows are duplicates of the others. For example, one of Speaker Boehner's trips to Jacksonville, Florida had 18 separate but identical filings. Why this occurs is unclear, but what is certain is that before we can study gift travel behavior, we must clean up what the Clerk gives us.

After deleting all the duplicate entries, we are left with 2721 unique trips made by members during the 114th Congress. (To see if the 114th Congress was a strange session for gift travel, I checked the 113th and 112th, and these Congresses also made around 2500 trips.) The first thing to note is that almost half of the original entries were duplicates. Whether this casts doubt over the accuracy of the reports is up for interpretation, but perhaps the high rate of duplication indicates an eagerness to comply with the Rules.

The win percentage data were provided by Professor Theriault, while the seniority, committee membership, and leadership data were taken from Wikipedia and cross-referenced with Ballotpedia. I adjusted the win percentage observations for those members in California who ran against copartisans in the general election because of California's unique primary system. Instead of being given 100% of the vote share, Democrats who defeated other Democrats, for example, were tallied as having won with whatever percentage they got in the general election. This adjustment corrects for what may have been an overestimate of the number of unopposed members. Party and ideology (roll-call summary) data were downloaded from the voteview.org website now under the auspices of Jeff Lewis. I use the Common Space DW-Nominate scores that were last updated 12 December 2016: these are called *ideology* in my outputs.

### Explanatory variables

I have operationalized leadership in three different ways, and it is important that the reader be clear as to what each means. *Leadership* is a dummy variable that equals 1 if the member is a party leader, committee chairman or ranking member; thus, this variable includes both Republicans and Democrats together. *Chairman* indicates whether the member was a committee chairman; it includes only Republicans because the GOP controlled the House during the 114th Congress. Its converse is *committee*, which includes only Democrats who were ranking members on their committees. Finally, there is *party leader*, which captures whether the member is Speaker, majority or minority leader, a whip, or chairman of either the Republican or Democratic caucus.  

### Dependent variable

We have one primary dependent variable: *trips* is a count of the number of separate journeys reported by each member to the Clerk of the House; each unique report counts as one trip. I have run the following analyses using a total count of the number of days spent traveling, and the results are substantively equivalent.

## Descriptive Statistics

After grouping all 2721 trips according to the members who went on those trips, we are left with a data set comprised of 439 rows, each representing a member. There are four extra members because some were replaced during the course of the Congress.

### Members; or, the Travelers

Let's start with some description of the members themselves. The average number of terms, our measure of seniority, is 5.7, sd = 4.3. The 114th Congress represented about the sixth term for the average member. The average win percentage was 70% with a standard deviation of 15 percentage points. A full 71 (16%) of the members were unopposed in their election; they won with 100% of the vote. The 114th Congress was dominated by the Republican Party, with 247 seats to the Democrats' 188. It was the largest majority the Republicans had controlled of the House since 1929 [@Bump2014].

Not all members went on gift travel during the 114th Congress, but most of them did. Nineteen of the 439 (4%) did not go on a single trip. Twenty-seven (6%) went on exactly one, 42 (9.5%) went on two, 50 (11%) went on three, with three being the mode. Figure 1 shows a histogram of the number of trips taken by all the members. The figure is heavily right-skewed (mean = 6.2, sd = 4.8, median = 5), with only five members going on 20 or more trips. The member to go on the most trips, 50, was Fred Upton (MI-R), both a committee chairman and a senior member. Louise Slaughter (NY-D), another senior member in a high-ranking committee position, though in the minority party, went on zero trips during the 114th Congress.

```{r, echo = F}
library(rio)
library(ggplot2)
df <- import("/Users/philipmoniz/Desktop/Supersafe incumbents paper/Super-safe incumbents/gift+s+b+ideology.csv")
g <- ggplot(df, aes(trips)) + geom_histogram(binwidth = 1)
g
```

Clearly the relationship between seniority and number of trips is not hard and fast, but Pearson's *r* correlations can give us a preliminary understanding of the relationships between the explanatory variables and our dependent variable, the number of gift-travel trips taken. Table 1 reports these correlations. The last two columns are the dependent variables. As can be seen in the *trips* column, more positive correlations are more closely associated with positions of power in the Congress than with seniority, ideology, or win percentage.

\begin{table}[!htbp] \centering 
  \caption{} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}} cccccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & winpct & seniority & ideology & leadership & committee & chairman & trips \\ 
\hline \\[-1.8ex] 
winpct & $1$ & $0.231$ & $$-$0.055$ & $0.111$ & $0.091$ & $0.088$ & $0.063$ \\ 
seniority & $0.231$ & $1$ & $$-$0.283$ & $0.401$ & $0.383$ & $0.173$ & $0.109$ \\ 
ideology & $$-$0.055$ & $$-$0.283$ & $1$ & $$-$0.037$ & $$-$0.057$ & $0.194$ & $0.203$ \\ 
leadership & $0.111$ & $0.401$ & $$-$0.037$ & $1$ & $0.911$ & $0.663$ & $0.336$ \\ 
committee & $0.091$ & $0.383$ & $$-$0.057$ & $0.911$ & $1$ & $0.689$ & $0.290$ \\ 
chairman & $0.088$ & $0.173$ & $0.194$ & $0.663$ & $0.689$ & $1$ & $0.340$ \\ 
trips & $0.063$ & $0.109$ & $0.203$ & $0.336$ & $0.290$ & $0.340$ & $1$ \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table}

#### Differences in Means

Two-sample t-tests can give us a first look at the question of whether the parties differ significantly in the amount of gift travel they go on, and lend some credence to the idea that the parties should be modeled separately. The first and most basic difference to note is that Democrats on average took 4.9 trips during the 114th Congress, while Republicans went on 7.13 trips on average. This difference is highly significant (p < .01). In terms of total days traveled, those two extra trips for Republicans amounts to about 5.5 days more away from Capitol Hill. The average Republican traveled for 27.2 days, and the average Democrat was gone for 21.7 (p < .01).

Whether the differences between the parties reflect party-specific behavior or simply the benefits of being the majority party will have to await further analysis. What we can say now is that there appears to be stark differences between party leadership and the rank and file: 11 trips on average for party leaders; 6.1 trips for the rank and file (p < .05). Leaders, just like Republicans as compared to Democrats, went on five more trips than rank-and-file members, but these five trips provided almost 16 more days on the road (41 vs 24.6 days, p < .05). Interestingly, leaders and rank-and-file members do not differ on the length of the average trip, which suggests that the reason for leaders' greater total of travel days is not because they took a few very long trips, say, to foreign countries. Leaders must simply take more ordinary journeys of around three days.

### Sponsors; or, the Givers

It's worth pausing to observe some basic facts about the organizations behind all this gift travel: the sponsors. During the 114th Congress, a total of 290 nongovernmental sources provided reimbursement for travel to members of Congress. A histogram of the number of trips provided per sponsor would show a large spike near one and then a small hill fading out toward 25, with tiny dots, few and far between, stretching all the way out to 600.

The average number of trips given by a sponsor is 9.7 (sd = 41.8, median = 1, 3rd quartile = 7). The most active sponsor, by far, is an organization called the Congressional Institute, which provided travel subsidies on 649 occasions. Judging from the reports, the Congressional Institute seems to invite great numbers of members, usually around 150 of them, to places near Washington, such as Hot Springs, VA. The Institute claims to advocate for congressional reform; for example, promoting the idea of a joint committee that will propose changes to rules and procedures followed in the House and Senate.

But the Congressional Institute is the outlier. Half of the sponsors gifted a single trip. State organizations such as the Massachusetts Farm Bureau Federation and Mississippi Dental Association populate this category. Seventy-nine sponsors (27%) gave between two and ten trips. These were organizations like the Semiconductor Industry Association and the West American Turkic Council. Among the big sponsors, those doling out more than ten trips, are recognizable names like Microsoft, the National Association of Broadcasters, each with 25, and the Consumer Electronics Association, with 59. The really heavy hitters, and the only three to crack 100 that are not the Congressional Institute, are the Heritage Foundation, the American Israeli Education Foundation, and the Aspen Institute. At a glance, it appears there may be a skew toward more conservative-leaning and business-affiliated organizations.

# Models and Results

Our main model representing congressional gift travel is linear and additive. I estimate the parameters using ordinary least squares, the results of which are reported in Table 2. Starting at the top of the table, we see two variables, among both parties, that are not statistically different from zero: win percentage and seniority. These null results are surprising because previous work on foreign travel has found significant effects for vote percentage and level of seniority on the number of country-days traveled as part of a Congressional Delegation [@Alduncin2017].

Our hypotheses that very safe members would be more attractive bets for sponsoring organizations turned out to be wrong. The same is true for the hypothesis that more senior members would be more popular among sponsors. These factors do not appear to matter for gift travel, but other variables may be at play.

Continuing down the table, we find significant results for all variables indicating high-ranking positions within the Congress or party. Being a committee chairman, which only Republicans were during the 114th, is predicted to provide 6.5 more trips than members who are not chairmen. The minority-party counterpart, being a ranking member of a committee, also has a positive effect for the number of trips Democrats take. The advantage that the Republican party has in its gift-travel rate can clearly by seen here. Compare the coefficient on *chairman* to that on *committee*. Being on a committee for the minority-party Democrats is associated with two more gift-travel trips, while being a chairman for the Republicans is associated with 6.5 more trips. Clearly, then, the majority party's control of the chairmanships seems to attract more sponsored travel.

\begin{table}[!htbp] \centering 
  \caption{Effects of Member Attributes on the Number of Gift-Travel Trips Taken in the 114th Congress} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{3}{c}{Number of Trips} \\ 
\cline{2-4} 
 & Republicans & Democrats & All Members \\ 
\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 winpct & $-$0.978 & $-$0.414 & 0.982 \\ 
  & (2.210) & (1.990) & (1.441) \\ 
  & & & \\ 
 seniority & 0.052 & 0.036 & 0.054 \\ 
  & (0.086) & (0.073) & (0.057) \\ 
  & & & \\ 
 chairman & 6.556$^{***}$ &  & 4.049$^{***}$ \\ 
  & (1.144) &  & (1.449) \\ 
  & & & \\ 
 committee &  & 2.090$^{**}$ & 2.508$^{**}$ \\ 
  &  & (1.017) & (1.085) \\ 
  & & & \\ 
 party.leaders & 5.234$^{**}$ & 1.728 & 4.138$^{**}$ \\ 
  & (2.138) & (2.366) & (1.604) \\ 
  & & & \\ 
 ideology & 2.106 & $-$9.323$^{***}$ & 2.019$^{***}$ \\ 
  & (2.017) & (3.105) & (0.508) \\ 
  & & & \\ 
 Constant & 5.900$^{***}$ & 1.051 & 4.484$^{***}$ \\ 
  & (1.709) & (1.371) & (1.020) \\ 
  & & & \\ 
\hline \\[-1.8ex] 
Observations & 250 & 189 & 439 \\ 
R$^{2}$ & 0.169 & 0.114 & 0.167 \\ 
Adjusted R$^{2}$ & 0.152 & 0.090 & 0.156 \\ 
Residual Std. Error & 4.702 (df = 244) & 3.896 (df = 183) & 4.419 (df = 432) \\ 
F Statistic & 9.897$^{***}$ (df = 5; 244) & 4.722$^{***}$ (df = 5; 183) & 14.468$^{***}$ (df = 6; 432) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table} 

A proper test of this interpretation would compare the gift-travel behavior under both Republican- and Democrat-controlled Congresses, but the Clerk's database goes only as far back as 2011. We would need data from 2010 in order to examine what patterns of travel behavior that emerged when the Democrats held a majority in the House of Representatives. As an alternative, we could check to see if the Republicans' advantage in gift travel persisted throughout every year of their three-Congress-long rule.

Lending some further support to the idea that sponsors privilege members with greater access to agenda control [@Cox2005] and other forms of control is the finding that being a party leader in the majority party means going on 5 additional trips while being a party leader in the minority is not statistically significant.

The estimates of the coefficients on the final explanatory variable in our model, ideology (or roll-call summary) are perhaps the most curious. The effect of a Republican member's ideology is nonsignificant: more conservative Republicans do not appear to travel less than their more moderate copartisans. This finding conflicts with Alduncin, Parker, and Theriault's [-@Alduncin2017] report of a negative relationship between increasing conservatism and frequency of travel. Those authors' results are estimated using a data set comprising 18 Congresses, while mine are based on a single Congress; therefore, we should be skeptical that my finding is robust across time. However, my finding may reflect an important difference between CODEL travel and gift travel.

The Democrats, on the other hand, seem to travel less on sponsorships the more conservative they are. To understand the magnitude of the coefficient on ideology, we should remember that a one-unit change in the DW-NOMINATE scale is very large and impossibly rare. The size of the range of values that Democrats exhibit on the scale is a mere .57. (The Republicans' is .67.) Which means that the most conservative (highest-scoring) Democrat is predicted to go on 5.3 ($.57 * -9.323$) fewer trips than the most liberal (lowest-scoring) Democrat. This is rather large effect, on par with the boost in travel that Republicans who chair committees enjoy.

Curiously, then, there is a penalty for Democrats with higher DW-NOMINATE scores, but no such penalty for similarly extreme Republicans. Given the current evidence, we can only speculate why this is the case, but it is striking that these results are the exact opposite as those found in Alduncin, Parker, and Theriault [-@Alduncin2017] regarding the relationship between ideological extremity and foreign travel among the two major parties. More conservative Republicans, they find, stay home while more liberal Democrats travel just as much as moderate Democrats.

# Discussion

There are two major limitations present in this study. First, my data come from a single Congress, so it is plausible that the relationships discovered here are merely an artifact of a single Congress. If we were to find that the relationships between our explanatory variables and members' travel behavior differed from Congress to Congress, we would be stuck in another pickle in which we would have to decide if we wanted to explain the variation within a given Congress or the variation across Congresses. As theory-generating scientists, we would presumably want to explain the variation we see over the long term, the kind of variation that is inherent to the Congress as an institution and not as a collection of 435 individuals.

Second, I have presented very little information regarding the character and behavior of the sponsors, who may be just as, if not more, important the members themselves in terms of who travels with whom and how often. Gift travel may require a theory of the sponsors' behavior more than or just as much as it does a theory of members' behavior. After all, the sponsors may be the more likely first-movers here. Theorizing about the sponsors may also increase our analytic leverage over the problem of the ever-changing composition of the House. From what we've learned here, it is likely that sponsors seek out higher-ranked members for gift travel, which suggests that there is some hope on the sponsors' part that something will be given in return for their generosity.

It is possible that if we devised a typology of sponsors, perhaps according to their ideology, whether they were pro-business or pro-consumer, international or domestic, we could pick up on some patterns of behavior that we could not detect by looking at the members. It might be, for example, that certain types of sponsor are targeting a specific kind of member for one reason or another, business groups for one reason, foreign-policy groups for another. We might find that all sponsors are gifting travel for the same reason, such as influencing policy, but that the members they choose depends how amenable an audience they expect the member to be.

If, as Hall and Deardorff [@Hall2006] suggest, interest groups and lobbyists provide information subsidies to likeminded legislators, then if we could find a measure of the likemindedness between sponsors and the members, we could find out whether or not their theory carries over to interest groups' gift-travel behavior. The evidence presented here says only that Democrats who lean more moderate are not treated to as much travel as their more liberal copartisans. The Hall and Deardorff thesis does not tell us whether we should expect moderate or extreme partisans to take more gift travel trips; it depends on the ideological makeup of the sponsoring organizations.

## Robustness Check

In an attempt to test the validity of my interpretations expounded above, I compiled a comparable data set for the 112th Congress. (The data were compiled in the same way as before, except with the seniority data coming from Charles Stewart's online repository.) This Congress is the earliest for which the Clerk of the House provides data, and these data allow us to examine gift-travel behavior at a time when the Democrats had only recently lost their majority to the Republicans in the elections of 2010. Therefore, we might expect the advantage exhibited by the majority-party Republicans in the 114th to be attenuated in the 112th.

\begin{table}[!htbp] \centering 
  \caption{Effects of Member Attributes on the Number of Gift-Travel Trips Taken in the 112th Congress} 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}}lccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{3}{c}{Number of Trips} \\ 
\cline{2-4} 
 & Republicans & Democrats & All Members \\ 
\\[-1.8ex] & (1) & (2) & (3)\\ 
\hline \\[-1.8ex] 
 winpct & $-$0.631 & 8.745$^{**}$ & 4.530$^{**}$ \\ 
  & (2.101) & (3.594) & (1.835) \\ 
  & & & \\ 
 seniority & 0.099 & $-$0.094 & $-$0.006 \\ 
  & (0.067) & (0.087) & (0.054) \\ 
  & & & \\ 
 chairman & 3.969$^{***}$ &  & 3.883$^{***}$ \\ 
  & (0.993) &  & (1.102) \\ 
  & & & \\ 
 committee &  & $-$0.046 & $-$0.138 \\ 
  &  & (1.363) & (1.163) \\ 
  & & & \\ 
 party.leader & 6.358$^{***}$ & $-$0.074 & 3.311$^{**}$ \\ 
  & (1.842) & (2.677) & (1.590) \\ 
  & & & \\ 
 ideology & 2.701$^{*}$ & $-$4.919 & $-$0.556 \\ 
  & (1.523) & (3.552) & (0.436) \\ 
  & & & \\ 
 Constant & 2.347 & $-$1.952 & 1.760 \\ 
  & (1.701) & (2.087) & (1.203) \\ 
  & & & \\ 
\hline \\[-1.8ex] 
Observations & 241 & 195 & 436 \\ 
R$^{2}$ & 0.136 & 0.069 & 0.058 \\ 
Adjusted R$^{2}$ & 0.118 & 0.044 & 0.045 \\ 
Residual Std. Error & 4.059 (df = 235) & 5.211 (df = 189) & 4.685 (df = 429) \\ 
F Statistic & 7.418$^{***}$ (df = 5; 235) & 2.794$^{**}$ (df = 5; 189) & 4.401$^{***}$ (df = 6; 429) \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
\end{tabular} 
\end{table}

As I said before, the fact that the players keep changing presents us with difficulty in comparing across Congresses; however, I think it is better to do so than not. It is important to note that a t-test reveals no significant difference in the number of trips taken by Democrats versus Republicans. Two Congresses later, with Republican control becoming a pattern, this had drastically changed.

Table 3 reports the estimates for the 112th Congress (2011-2012). The first thing to notice is that the effects of being a committee chairman or a party leader are sizable and significant, just as in the 114th Congress. The effect of ideology is marginally significant this time $(p < .08)$, but it is in the opposite direction as expected. Greater conservatism among Republicans is associated with more gift-travel trips. It is at least consistent with the estimates of the 114th Congress in that ideological extremity among Republicans is not penalized.

The estimates for the Democrats' equation are more disconcerting. Neither being a ranking member on a committee nor being more ideologically extreme has a significant effect on the number of trips taken. Those members who had previously been chairmen were now relegated to ranking members, and sponsors seemed to have abandoned them for their counterparts in the majority party. Or it could be that travel gifts among Democrats were more "democratized," with everyone getting some.

While seniority remains insignificant, as it was in the 114th, win percentage emerges as a significant effect for the Democrats. What to make of this? Since we are looking at the 112th Congress simply as a comparison for the 114th, all we should say at this point is that it is plausible that during different Congresses, different member attributes may matter.

For the most part, we have found consistency, at least among the Republicans (or majority party): party and committee leadership matter for the Republicans, and extreme ideology is no deterrent, while seniority and win percentage do not matter. Among Democrats, the story is one of dissimilarity, except for the continued insignificance of seniority. Across these two Congresses at least, party and committee leadership do not appear to be consistent attractors of gift travel. Excessive moderateness in the 114th was a repellant, while high winning percentages was an attractant in the 112th.

The last consistency worth noting concerns model fit. The adjusted $R^2$ was consistently higher for the Republican models versus the Democratic models. The higher model fit for the Republican models may reflect the fact that these explanatory variables better explain the variance in gift travel within the majority party, or it could be something more intrinsic to the Republican party. Further research that exploits variation in who controls the House would help shed light on this and other questions left unanswered in this analysis.

# Conclusion

A proper continuation of Alduncin, Parker, and Theriault's work [-@Alduncin2014; -@Alduncin2017] would examine who travels with whom and how often. Using what the Clerk of the House provides, we could determine which members were visiting the same locations at the same times, and use this information to investigate how member-level attributes relate to the partisan nature of their gift-travel behavior. Many trips gifted during the 114th Congress involved members traveling together, and we still have yet to find out if party polarization's effect on CODEL travel is felt also on gift travel.

Gift travel is an overlooked aspect of members' relationships with interest groups and non-governmental organizations. Many questions are still unanswered. How does gift travel change over time? What's it good for? Researchers should appreciate the potentially important things we have to learn from this unusual form of documented lobbying and travel.

# References
